### ISSUE TITLE
Device Name Displays with Strange Numbers

### ISSUE THREAD

**Issue by JaySuNTU** [Lzzz666/multi-stream-platform#6]
When displaying the device name on the screen, it sometimes shows strange numbers. I would like to understand why this happens.

![image](https://github.com/user-attachments/assets/ad33d4f5-c86b-4bd4-b9fe-42e3f64e1396)

**Comment by Lzzz666** [comment]
It is device label.
![image](https://github.com/user-attachments/assets/db3524e3-13df-4148-91ee-3c39336aa182)

**Comment by JaySuNTU** [comment]
Well noted
